### ISSUE TITLE
Summary extraction documentation is missing and some recommendation for it

### ISSUE THREAD

**Issue by xiaohan2012** [dnmilne/wikipediaminer#23]
It seems that the Wiki is lacking the documentation for how to do summary extraction. 

[Here](https://github.com/semanticize/semanticizer/wiki/Notes-on-the-wikipedia-miner-dump-processing-on-Hadoop) is some resources on how to do that found on [semanticizer](https://github.com/semanticize/semanticizer/).

Better to add that in the current wiki.

Thanks

**Comment by Neuw84** [comment]
You mean this? https://github.com/dnmilne/wikipediaminer/wiki/Obtaining-wikipedia-data

**Comment by xiaohan2012** [comment]
Ah, careless me. There it is!

Thanks
